# Suppress JDA logging
org.slf4j.simpleLogger.log.net.dv8tion.jda=WARN
org.slf4j.simpleLogger.defaultLogLevel=WARN
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false